# Generates pretty snake animation, using @Platane's awesome snk action
name: 🐍 Generate Snake Contribution GIF
on:
  # run on every push on the master branch
  # push:
  #   branches:
  #   - main
  workflow_dispatch: # Manual dispatch
  schedule:
    - cron: '30 23 * * *' # Runs at 23:30 every day.
jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Generate Snake GIF
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
          assets/github-snake.svg
          assets/github-snake-dark.svg?palette=github-dark
          assets/github-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      # Commit the changes
      - name: Commit files
        run: |
          git config user.email "rakeshhniraulaa@gmail.com"
          git config user.name "rakesh"
          git add .
          git commit -m ":snake: update snake contribution animation"
      # Push the changes
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BOT_GITHUB_TOKEN }}
          branch: ${{ github.ref }}
