# Generates pretty snake animation, using @Platane's awesome snk action
name: 🐍 Generate Snake Contribution GIF
on:
  # run on every push on the master branch
  # push:
  #   branches:
  #   - main
  workflow_dispatch: # Manual dispatch
  schedule:
    - cron: '30 23 * * *' # Runs at 23:30 every day.
jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Generate Snake GIF
        uses: Platane/snk@v3
        with:
          # GitHub username to read the contribution graph from (required)
          github_user_name: ${{ github.repository_owner }}

          # List of files to generate.
          # One file per line. Each output can be customized with options as query string.
          # Supported options:
          # - palette:     A preset color, one of [github, github-dark, github-light]
          # - color_snake: Color of the snake
          # - color_dots:  Comma-separated list of dot colors.
          #                The first one is for 0 contribution, then it goes from the low contribution to the highest.
          #                Exactly 5 colors are expected.
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

        env:
          # A GitHub token is required to fetch the contribution calendar from the GitHub API
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
